# Generated by Django 5.0.1 on 2024-01-25 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='female',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_female', models.CharField(blank=True, default='test', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='male',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_male', models.CharField(blank=True, default='test', max_length=50, null=True)),
                ('girls', models.OneToOneField(default='test', null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.female')),
            ],
        ),
    ]
