# Generated by Django 5.0.1 on 2024-01-25 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='female',
            name='name_female',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='male',
            name='girls',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.female'),
        ),
        migrations.AlterField(
            model_name='male',
            name='name_male',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.product')),
            ],
        ),
    ]
