# Generated by Django 5.0.1 on 2024-02-07 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_watcher_watch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='male',
            name='girls',
        ),
        migrations.RemoveField(
            model_name='user',
            name='products',
        ),
        migrations.RemoveField(
            model_name='watcher',
            name='watch',
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image_book', models.ImageField(blank=True, null=True, upload_to='photos/%y/%m/%d')),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('photo_author', models.ImageField(blank=True, null=True, upload_to='photos/%y/%m/%d')),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('retal_price_day', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('retal_period', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, choices=[('available', 'available'), ('rental', 'rental'), ('sold', 'sold')], max_length=50, null=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.category')),
            ],
        ),
        migrations.DeleteModel(
            name='female',
        ),
        migrations.DeleteModel(
            name='male',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='user',
        ),
        migrations.DeleteModel(
            name='vedio',
        ),
        migrations.DeleteModel(
            name='watcher',
        ),
    ]
