# Generated by Django 5.0.1 on 2024-01-25 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
