# Generated by Django 5.0.1 on 2024-02-07 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_delete_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
    ]
